# DOCKERFILE FOR NVIDIA 

FROM nvcr.io/nvidia/pytorch:24.03-py3

# SPECIFY YOUR WORKING DIR

WORKDIR /home/

# COPY ALL THE DATA NECCESSARY FROM YOUR MACHINE

COPY ./ .

# RUN ALL THE COMMANDS NEEDED AT THE START

RUN apt update
