seed_everything: 45

model:
  class_path: models.ConvolutionalAutoencoderSC16Long
  init_args:
    bottleneck: 2

data:
  class_path: data.SubcubeDataModule
  init_args:
    data_directories: ["/home/ace/Documents/DATA/prp_files"]
    extension: '.hdf5'
    sc_side_length: 32
    stride: 16
    indexing: CoreSliceCubeIndex
    physical_parameters: ['dens']
    batch_size: 32
    num_workers: 2
    shuffle: True
    flip: 0.5
    crop_size: 16

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: min
    factor: 0.1
    patience: 500
    cooldown: 500
    min_lr: 1.e-5
    monitor: train_loss
    verbose: True

trainer:
  max_epochs: -1
  accelerator: cpu
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: frankencube
      log_model: True
  # devices: 4
  # precision: 32

# ckpt_path: '/root/FrankenCube/frankencube/rohy8i66/checkpoints/epoch=4-step=40010.ckpt'
