seed_everything: 45

model:
  class_path: models.ConvolutionalAutoencoderSC16
  init_args:
    bottleneck: 2
    log_offset: 25
    vmin: 0
    vmax: 10

data:
  class_path: data.SubcubeDataModule
  init_args:
    data_directories: ["/root/prp_files"]
    extension: '.hdf5'
    sc_side_length: 32
    stride: 16
    indexing: CoreSliceCubeIndex
    physical_parameters: ['dens']
    batch_size: 32
    num_workers: 20
    shuffle: True
    flip: 0.5
    crop_size: 16

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: min
    factor: 0.1
    patience: 500
    cooldown: 500
    min_lr: 1.e-5
    monitor: train_loss
    verbose: True

trainer:
  max_epochs: 5
  accelerator: gpu
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: frankencube
      log_model: True
  # devices: 4
  # precision: 32

# ckpt_path: spitzer_model.ckpt
